routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::redirect('/', '/artist/login');
Route::redirect('/artist', '/artist/login');
Route::post('/pubsub', [\App\Http\Controllers\PubsubController::class, 'subscribe']);
route::get('/artist/login', [\App\Http\Controllers\HomeController::class, 'artistLogin'])->middleware(['checkAuthenticated']);

Route::group(['prefix' => '/artist', 'middleware' => ['auth', 'verified', 'checkUserStatus', 'role:artist']], function () {

    // Dashboard
    Route::group(['prefix' => '/dashboard'], function () {
        Route::get('/', [App\Http\Controllers\Artist\DashBoardController::class, 'index'])->name('artist.dashboard');
        Route::get('/purchase/detail/{id}', [App\Http\Controllers\Artist\DashBoardController::class, 'purchaseDetail'])->name('artist.dashboard.buyerDetail');
        Route::get('/salesReport/{report}', [App\Http\Controllers\Artist\DashBoardController::class, 'salesReport'])->name('artist.dashboard.salesReport');
    });

    // Profile
    Route::group(['prefix' => '/profile'], function () {
        Route::get('/', [App\Http\Controllers\Artist\ArtistProfileController::class, 'index'])->name('artist.profile');
        Route::view('/update/password', 'artist.auth.password.updatePassword');
        Route::post('/update', [App\Http\Controllers\Artist\ArtistProfileController::class, 'update'])->name('artist.profile.update');
    });

    // Song
    Route::group(['prefix' => '/song'], function () {
        Route::post('/', [App\Http\Controllers\Artist\SongController::class, 'store'])->name('artist.song');
        Route::delete('/{id}', [App\Http\Controllers\Artist\SongController::class, 'delete'])->name('artist.song.delete');
        Route::get('/{id}', [App\Http\Controllers\Artist\SongController::class, 'show'])->name('artist.song.show');
        Route::post('/update', [App\Http\Controllers\Artist\SongController::class, 'update'])->name('artist.song.update');
    });

    // Album
    Route::group(['prefix' => '/album'], function () {
        Route::post('/', [App\Http\Controllers\Artist\AlbumController::class, 'store'])->name('artist.album');
        Route::get('/listTheSong/{artistId}', [App\Http\Controllers\Artist\AlbumController::class, 'listTheSong'])->name('artist.listTheSong');
        Route::get('/detail/{id}', [App\Http\Controllers\Artist\AlbumController::class, 'albumDetail'])->name('artist.detail');
        Route::post('/select/song', [App\Http\Controllers\Artist\AlbumController::class, 'selectSong'])->name('artist.select.song');
        Route::delete('/{id}', [App\Http\Controllers\Artist\AlbumController::class, 'delete'])->name('artist.album.delete');
        Route::delete('/song/{id}', [App\Http\Controllers\Artist\AlbumController::class, 'removeSong'])->name('artist.album.song.delete');
        Route::get('/{id}', [App\Http\Controllers\Artist\AlbumController::class, 'show'])->name('artist.show');
        Route::get('/albumStatus/{id}', [App\Http\Controllers\Artist\AlbumController::class, 'AlbumStatus'])->name('artist.paid.status');
        Route::post('/update', [App\Http\Controllers\Artist\AlbumController::class, 'update'])->name('artist.album.update');
    });

    // Notification
    Route::group(['prefix' => '/notification'], function () {
        Route::get('/', [App\Http\Controllers\Artist\NotificationController::class, 'index'])->name('artist.notification');
        Route::post('/', [App\Http\Controllers\Artist\NotificationController::class, 'store'])->name('artist.notification.store');
        Route::get('/{id}', [App\Http\Controllers\Artist\NotificationController::class, 'show'])->name('artist.notification.show');
        Route::delete('/{id}', [App\Http\Controllers\Artist\NotificationController::class, 'delete'])->name('artist.notification.delete');
    });
    // Withdrawal Earning
    Route::group(['prefix' => '/withdrawal/earning'], function () {
        Route::get('/', [App\Http\Controllers\Artist\WithdrawalEarnnigController::class, 'index'])->name('artist.WithdrawalEarnnig');
        Route::post('/store/account', [App\Http\Controllers\Artist\CardController::class, 'store'])->name('artist.WithdrawalEarnnig.card.store');
        Route::get('/account/detail/{id}', [App\Http\Controllers\Artist\CardController::class, 'show'])->name('artist.WithdrawalEarnnig.card.show');
        Route::post('/update/account', [App\Http\Controllers\Artist\CardController::class, 'update'])->name('artist.WithdrawalEarnnig.card.update');
        Route::post('/', [App\Http\Controllers\Artist\WithdrawalEarnnigController::class, 'withdrawalRequest'])->name('artist.Withdrawal');
        Route::post('/again', [App\Http\Controllers\Artist\WithdrawalEarnnigController::class, 'withdrawalRequestAgain'])->name('artist.Withdrawal.again');
    });
    //Preorder
    Route::group(['prefix' => '/preorder'], function () {
        //PreOrder Song
        Route::group(['prefix' => '/song'], function () {
            Route::post('/', [App\Http\Controllers\Artist\SongPreorderController::class, 'store'])->name('artist.preorder.song');
            Route::delete('/{id}', [App\Http\Controllers\Artist\SongPreorderController::class, 'delete'])->name('artist.preorder.song.delete');
            Route::get('/{id}', [App\Http\Controllers\Artist\SongPreorderController::class, 'show'])->name('artist.preorder.song.show');
            Route::post('/update', [App\Http\Controllers\Artist\SongPreorderController::class, 'update'])->name('artist.preorder.song.update');
            Route::get('/buyerList/{id}', [App\Http\Controllers\Artist\SongPreorderController::class, 'preorderSongPurchaseList'])->name('artist.preorder.song.buyerList');
        });
        //PreOrder Album
        Route::group(['prefix' => '/album'], function () {
            Route::post('/', [App\Http\Controllers\Artist\AlbumPreorderController::class, 'store'])->name('artist.preorder.album');
            Route::post('/song', [App\Http\Controllers\Artist\AlbumPreorderController::class, 'storeAlbumSong'])->name('artist.preorder.album.song');
            Route::post('/song/update', [App\Http\Controllers\Artist\AlbumPreorderController::class, 'updateAlbumSong'])->name('artist.preorder.album.song.update');
            Route::delete('/song/{id}', [App\Http\Controllers\Artist\AlbumPreorderController::class, 'removeAlbumSong'])->name('artist.preorder.album.song.delete');
            Route::delete('/{id}', [App\Http\Controllers\Artist\AlbumPreorderController::class, 'delete'])->name('artist.preorder.album.delete');
            Route::get('/{id}', [App\Http\Controllers\Artist\AlbumPreorderController::class, 'show'])->name('artist.preorder.album.show');
            Route::post('/update', [App\Http\Controllers\Artist\AlbumPreorderController::class, 'update'])->name('artist.preorder.album.update');
            Route::get('/buyerList/{id}', [App\Http\Controllers\Artist\AlbumPreorderController::class, 'preorderAlbumPurchaseList'])->name('artist.preorder.Album.buyerList');
        });
        Route::get('/albumSong/{id}', [App\Http\Controllers\Artist\AlbumPreorderController::class, 'getPreorderSong'])->name('artist.preorder.albumSong');
    });
    Route::get('/earningStats/item/{id}', [App\Http\Controllers\Artist\EarningStatsController::class, 'purchaseItemDetail'])->name('artist.purchase.itemDetail');
    Route::get('/terms-conditions', [App\Http\Controllers\Artist\TermsAndConditionsController::class, 'index'])->name('artist.terms');
    Route::get('/privacy-policies', [App\Http\Controllers\Artist\PrivacyAndPolicyController::class, 'index'])->name('artist.policy');
    Route::post('/carbon/date/{id}', [App\Http\Controllers\Artist\SongPreorderController::class, 'carbonDate'])->name('artist.preorder.carbonDate');
});


Route::get('/fetchData', [App\Http\Controllers\HomeController::class, 'anyData'])->name('datatables.data');
Route::get('/getUsers', [App\Http\Controllers\HomeController::class, 'getUsers'])->name('listing');

Route::redirect('/admin', '/admin/login');
Route::get('/admin/login', [\App\Http\Controllers\HomeController::class, 'loginPage'])->name('admin.login')->middleware('checkAuthenticated');
Route::get('/admin/forgot-password', [\App\Http\Controllers\HomeController::class, 'forgetPassword']);
Route::group(['prefix' => '/admin', 'middleware' => ['role:admin', 'auth']], function () {
    /*============================Admin auth routes goes here========================== */

    Route::get('/dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('admin.dashboard');
    Route::get('/dashboard/salesReport/{report}', [App\Http\Controllers\Admin\DashboardController::class, 'salesReport'])->name('admin.dashboard.salesReport');

    Route::get('/changePassword', [\App\Http\Controllers\Admin\AuthController::class, 'changePassword']);
    Route::post('change-password', [\App\Http\Controllers\Admin\AuthController::class, 'updatePassword'])->name('change.password');
    /*==============================================App users Routes============================================= */
    Route::resource('users', \App\Http\Controllers\Admin\UserController::class);
    Route::get('/userBlock/{id}', [App\Http\Controllers\Admin\UserController::class, 'userBlock'])->name('userBlock');
    Route::get('users/detail/{id}/details', [\App\Http\Controllers\Admin\UserController::class, 'listing']);
    Route::get('usersDetail/{id}', [\App\Http\Controllers\Admin\UserController::class, 'userDetail']);
    Route::post('users/update/{id}', [\App\Http\Controllers\Admin\UserController::class, 'update']);

resources/views/partialPages/sidebar/adminSidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4 text-xs" style="background-color: #ba011a;">
    <!-- Brand Logo -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-1  pb-0 mb-0 d-flex" style="margin-top: 4px !important;">
            <div class="text-center">
                <div class="row d-flex align-items-center">
                    <p class="" style="margin-left: 30px;color: white;font-size: 15px;margin-top: 1px !important;">Q the Music</p>
                </div>
            </div>
        </div>
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item width180">
                    <a href="{{ route('admin.dashboard')}}"  class="nav-link white-color width180">
                        <i class=""></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>
                <li class="nav-item width180">
                    <a href="{{ route('users.index')}}" class="nav-link white-color width180">
                        <i class=""></i>
                        <p>
                            App Users
                        </p>
                    </a>
                </li>
                <li class="nav-item width180">
                    <a href="{{url('admin/categories/')}}" class="nav-link white-color width180">
                        <i class=""></i>
                        <p>
                            Category
                        </p>
                    </a>
                </li>
                <li class="nav-item width180">
                    <a href="{{url('admin/notifications')}}" class="nav-link white-color width180">
                        <i class=""></i>
                        <p>
                            Notifications
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link white-color width180">
                        <i class=""></i>
                        <p>
                            Artists
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="ml-1 nav nav-treeview">
                      <li class="nav-item">
                        <a href="{{ route('activeArtists') }}" class="nav-link white-color width180">
                            <i class=""></i>
                            <p class="ml-2">Actives Artists</p>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a href="{{ route('blockArtists') }}" class="nav-link white-color width180">
                            <i class=""></i>
                            <p class="ml-2">Blocked Artists</p>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a href="{{ route('admin.artist.notification') }}" class="nav-link white-color width180">
                            <i class=""></i>
                            <p class="ml-2">Notifications</p>
                        </a>
                      </li>
                    </ul>
                </li>
                <li class="nav-item width180">
                    <a href="{{ route('admin.packages')}}" class="nav-link white-color width180">
                        <i class=""></i>
                        <p>
                            Packages
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link white-color width180">
                        <i class=""></i>
                        <p>
                            Earnings
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="ml-1 nav nav-treeview">
                      <li class="nav-item">
                        <a href="{{ route('admin.purchased.history') }}" class="nav-link white-color width180">
                            <i class=""></i>
                            <p class="ml-2">Purchased History</p>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a href="{{ route('admin.artist.earning') }}" class="nav-link white-color width180">
                            <i class=""></i>
                            <p class="ml-2">Artist Earnings</p>
                        </a>
                      </li>
                    </ul>
                </li>
                <li class="nav-item width180">
                    <a href="{{ url('admin/content-type/create?content_type=TermAndCondition') }}" class="nav-link white-color width180">
                        <i class=""></i>
                        <p>
                            Terms & Conditions
                        </p>
                    </a>
                </li>
                <li class="nav-item width180">
                    <a href="{{ url('admin/content-type/create?content_type=PrivacyPolicy') }}" class="nav-link white-color width180">
                        <i class="nav-icon "></i>
                        <p>
                            Privacy policy
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{url('telescope')}}"
                       class="nav-link white-color width180 {{ (request()->is('telescope/*')) ? 'active-nav' : '' }}" target="_blank">
                        <p>
                            <i class="nav-icon "></i>

                            Telescope
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

resources/views/partialPages/sidebar/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{url('/')}}" class="brand-link">
        <img src="{{asset('img/logo/logo.svg')}}" alt="TechSwivel" class="brand-image  elevation-3" style="opacity: .8">
<br>
{{--        <span class="brand-text font-weight-light text-center"></span>--}}
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <a href="#" class="d-block">{{auth()->user()->name? auth()->user()->name : "Administrator"}}</a>
            </div>
            <div class="info">
{{--                <a href="#" class="d-block">{{auth()->user()->name? auth()->user()->name : "Administrator"}}</a>--}}

            </div>
        </div>


        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="{{url('home')}}" class="nav-link {{ (request()->is('/home')) ? 'active' : '' }}">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{url('telescope')}}"
                       class="nav-link {{ (request()->is('telescope/*')) ? 'active' : '' }}" target="_blank">
                        <i class="nav-icon fas fa-th"></i>
                        <p>
                            Telescope
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{url('getUsers')}}" class="nav-link {{ (request()->is('getUsers')) ? 'active' : '' }}">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                             Users
                        </p>
                    </a>
                </li>
                @if(env('IS_CONFIGURATION_VISIBLE'))
                    <li class="nav-item">
                        <a href="{{url('artisan-login')}}" class="nav-link  {{ (request()->is('artisan/*')) ? 'active' : '' }}" target="_blank">
                            <i class="nav-icon fa fa-cog"></i>
                            <p>
                            Configurations
                            </p>
                        </a>
                    </li>
                @endif
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>